---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: package-aws-alb-ingress-controller
  namespace: argocd

  # finalizers:  # Add a this finalizer ONLY if you want these to cascade delete.
  #   - resources-finalizer.argocd.argoproj.io  

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  source:

    # New chart v2.X in new helm repo
    repoURL: 'http://storage.googleapis.com/kubernetes-charts-incubator'
    targetRevision: 1.0.2
    chart: aws-alb-ingress-controller
    

    helm:
      # Release name override (defaults to application name)
      releaseName: aws-alb-ingress-controller

      parameters:
      - name: 'clusterName'
        value: rparrott-sandbox
      - name: 'autoDiscoverAwsRegion'
        value: "true"
      - name: 'autoDiscoverAwsVpcID'
        value: "true"

  # Sync policy
  syncPolicy:
    automated:
      # Specifies if resources should be pruned during auto-syncing ( false by default ).
      prune: true 

      # Specifies if partial app sync should be executed when resources are 
      #   changed only in target Kubernetes cluster and no git change detected 
      #   ( false by default ).
      selfHeal: false 


