---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: package-aws-cluster-autoscaler
  namespace: argocd

  # finalizers:  # Add a this finalizer ONLY if you want these to cascade delete.
  #   - resources-finalizer.argocd.argoproj.io  

spec:

  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  source:

    # New chart v2.X in new helm repo
    repoURL: 'https://kubernetes.github.io/autoscaler'
    targetRevision: 1.0.2
    chart: cluster-autoscaler-chart

    helm:
      # Release name override (defaults to application name)
      releaseName: cluster-autoscaler

      parameters:
      - name: 'autoDiscovery.clusterName'
        value: rparrott-sandbox

      # values: |

      #   metricsScraper:
      #     enabled: true

      #   metrics-server:
      #     enabled: true


  # Sync policy
  syncPolicy:
    automated:
      # Specifies if resources should be pruned during auto-syncing ( false by default ).
      prune: true 

      # Specifies if partial app sync should be executed when resources are 
      #   changed only in target Kubernetes cluster and no git change detected 
      #   ( false by default ).
      selfHeal: false 